# Generated by Django 4.0.7 on 2022-11-23 05:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_todos'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='todos',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todos',
            name='created_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 5, 27, 38, 413210, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todos',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='todos',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
